const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
// Run the component's actual scene callbacks with controlled React state setters.
const source = fs.readFileSync(process.argv[2] || 'components/showcase/ShowcaseStage.tsx', 'utf8');
const ast = ts.createSourceFile('ShowcaseStage.tsx', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
let options;
function visit(node) {
  if (ts.isCallExpression(node) && node.expression.getText(ast) === 'createShowcaseScene') options = node.arguments[0];
  ts.forEachChild(node, visit);
}
visit(ast);
assert(options, 'component must create a scene');
const names = ['onProgress', 'onReady', 'onContextLost', 'onError'];
const callbacks = options.properties.filter(p => names.includes(p.name?.getText(ast))).map(p => p.getText(ast)).join(',\n');
const js = ts.transpileModule(`module.exports = function(rebuild, fallback = 'fine', bootstrapPreview = false, promoteOk = true) {
 let cancelled = false, recoveryRequested = false;
 let initialReady = false;
 const cfg = {assets:{model:'fixture.glb'}};
 const initialQuality = bootstrapPreview ? 'fast' : 'original';
 const requestedQuality = 'original', requestedAsset = 'full.glb';
 const requestedWireMode = 'native';
 const qualitySwitchRef = {current:0}, appliedModelRef = {current:'preview'}, pendingModelRef = {current:null};
 const handle = {setModel: next => {state.promoted = next; return Promise.resolve(promoteOk)}};
 const handleRef = {current:handle};
 const qualityModel = model => model;
 const constrainedGraphics = () => false;
 const wrap = {after: () => {}};
 const setQualityLoading = v => state.qualityLoading = v;
 const setAppliedTextureQuality = v => state.appliedQuality = v;
 const setQualityError = v => state.qualityError = v;
 const window = {requestAnimationFrame: cb => {state.promoteFrame = cb}, setTimeout: (cb, delay) => {if (delay === 400) state.promoteTimer = cb}};
 const saveResumeFrame = () => {};
 const primeModelAsset = () => {};
 let upgradeTimer = null;
 const state = { ready: true, ratio: 1, error: null, rebuild, drops: 0 };
 const setReady = v => state.ready = v;
 const setLoadRatio = v => state.ratio = v;
 const setError = v => state.error = v;
 const setRebuild = update => state.rebuild = update(state.rebuild);
 const dropFreeze = () => state.drops++;
 const initialKey = "fixture-v1-original";
 const rememberLoadedModel = key => state.receipt = key;
 const setLoadingKey = key => state.loadingKey = key;
 const recoveryQuality = () => fallback;
 const rememberWorkingQuality = (asset, quality) => state.working = quality;
 const configRef = {current:{assets:{model:'fixture.glb'}}};
 const TEXTURE_QUALITY = {original:{size:16384,label:'RAW'},fine:{size:4096,label:'4K'},balanced:{size:2048,label:'2K'},fast:{size:1024,label:'1K'}};
 const textureQualityRef = { current: 'original' }, wireRef = { current: {mode:'native'} }, inspectorRef = {current:false};
 const setTextureQuality = v => state.quality = v;
 const setWireMode = () => {}; const setInspector = () => {}; const setWirePanelOpen = () => {}; const setMemoryNotice = () => {};
 return { state, appliedModelRef, pendingModelRef, cancel: () => cancelled = true, callbacks: {${callbacks}} };
};`, {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const mod = {exports:{}};
new Function('module', js)(mod);
const make = mod.exports;
const capped = make(4);
capped.callbacks.onContextLost();
assert(capped.state.error, 'exhausted recovery must show an actionable error, never an endless 100% loader');
assert.equal(capped.state.ratio, 0);
assert.equal(capped.state.rebuild, 4);
capped.callbacks.onReady();
assert.equal(capped.state.ready, false, 'late ready from the failed scene cannot dismiss its error');
for (let n = 0; n < 4; n++) {
 const attempt = make(n);
 attempt.callbacks.onContextLost();
 assert.equal(attempt.state.rebuild, n + 1);
 assert.equal(attempt.state.ratio, 0);
 attempt.callbacks.onContextLost();
 assert.equal(attempt.state.rebuild, n + 1, 'lost/restored and repeated render failures count once per scene');
 attempt.callbacks.onProgress(1);
 attempt.callbacks.onReady();
 attempt.callbacks.onError('late error');
 assert.equal(attempt.state.ready, false);
 assert.equal(attempt.state.ratio, 0);
 assert.equal(attempt.state.error, null);
}
const unknown = make(0, null); unknown.callbacks.onContextLost();
assert(unknown.state.error); assert.equal(unknown.state.quality, undefined,'no verified fallback must never guess 1K');
assert.equal(unknown.state.rebuild,0,'no repeated loading of a failed quality');
const known = make(0, 'balanced'); known.callbacks.onContextLost();assert.equal(known.state.quality,'balanced','only an actual rendering failure may roll back to a proven quality');
const ordinaryError = make(0, 'balanced'); ordinaryError.callbacks.onError('HTTP 404');assert.equal(ordinaryError.state.quality,undefined,'ordinary load failures preserve the preference');
const loaded = make(0);
loaded.callbacks.onProgress(1);
assert.equal(loaded.state.ratio, .99, 'bytes received is not model ready');
loaded.callbacks.onReady();
assert.equal(loaded.state.ratio, 1);
assert.equal(loaded.state.ready, true);
assert.equal(loaded.state.drops, 1);
loaded.callbacks.onReady();
assert.equal(loaded.state.drops, 1, 'later model swaps must not repeat initial ready handling');
assert.equal(loaded.state.receipt, 'fixture-v1-original');
assert.equal(loaded.state.loadingKey, null);
const stale = make(0);
stale.cancel();
const before = {...stale.state};
for (const [name, arg] of [['onProgress',.5],['onReady'],['onError','obsolete'],['onContextLost']]) stale.callbacks[name](arg);
assert.deepEqual(stale.state, before, 'disposed scene callbacks cannot overwrite current loading state');
console.log('PASS recovery cap, duplicate failures, late callbacks, download/ready distinction, successful completion');

const progressive = make(0, 'fine', true);
progressive.callbacks.onReady();
assert.equal(progressive.state.working, 'fast', 'preview success must not falsely register RAW as working');
assert.equal(typeof progressive.state.promoteTimer, 'function', 'full model promotion waits after preview readiness');
assert.equal(progressive.state.promoted, undefined);
progressive.state.promoteTimer();
assert.equal(typeof progressive.state.promoteFrame, 'function', 'promotion also waits until the next animation frame');
progressive.state.promoteFrame();
assert.equal(progressive.state.promoted.asset, 'full.glb');
progressive.callbacks.onReady();
assert.equal(progressive.state.drops, 1, 'full model readiness cannot repeat the initial transition');
Promise.resolve().then(() => {
 assert.equal(progressive.state.qualityLoading, false);
 assert.equal(progressive.state.qualityError, false);
 assert.equal(progressive.state.receipt.includes('full.glb'), true);
 console.log('PASS preview-first ready and deferred RAW promotion');
 const failed = make(0, 'fine', true, false);
 failed.callbacks.onReady();
 failed.state.promoteTimer();
 failed.state.promoteFrame();
 return Promise.resolve().then(() => {
  assert.equal(failed.state.qualityError, true, 'failed promotion must expose retry');
  assert.equal(failed.state.appliedQuality, 'fast', 'failed promotion keeps the visible preview quality');
  assert.equal(failed.appliedModelRef.current, 'preview', 'failed promotion cannot claim full model is displayed');
  assert.equal(failed.pendingModelRef.current, null, 'failed target is cleared for retry');
  console.log('PASS failed RAW promotion leaves previous model and retry state');
 });
}).catch(error => { console.error(error); process.exitCode = 1; });
