const assert = require('node:assert/strict');
const fs = require('node:fs'), ts = require('typescript'), Module = require('node:module');
const m = new Module(__filename, module);
m._compile(ts.transpileModule(fs.readFileSync('components/showcase/modelMemory.ts','utf8'), { compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020} }).outputText,__filename);
const {decodedTextureBytes,textureLimit,queueModelLoad,budgetImageDecoding,disposeModel,beginHeavyLoad,finishHeavyLoad,interruptedHeavyLoad}=m.exports;
class Canvas {constructor(){this.width=1;this.height=1}getContext(){return {drawImage(){}}}}
global.HTMLCanvasElement=Canvas;global.document={createElement:()=>new Canvas()};
const entries=new Map();global.sessionStorage={getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)};
(async()=>{
const imageHeader = Buffer.alloc(24); imageHeader.writeUInt32BE(0x89504e47); imageHeader.writeUInt32BE(4096,16); imageHeader.writeUInt32BE(4096,20);
const jsonString=JSON.stringify({images:[{bufferView:0}],bufferViews:[{buffer:0,byteLength:24}]});
const json=Buffer.from(jsonString+' '.repeat((4-jsonString.length%4)%4));
const glb=Buffer.alloc(28+json.length+24);glb.writeUInt32LE(0x46546c67);glb.writeUInt32LE(json.length,12);json.copy(glb,20);imageHeader.copy(glb,28+json.length);
assert.equal(decodedTextureBytes(glb.buffer.slice(glb.byteOffset,glb.byteOffset+glb.length)),4096*4096*4*4/3,'budget comes from pixels, not compressed bytes');
assert.equal(decodedTextureBytes(new ArrayBuffer(2)),null,'unknown images must not bypass original memory guard');
assert.equal(textureLimit(16384,8192,16,true),8192,'RAW must never silently become 1K');
assert.equal(textureLimit(2048,8192,16,true),1024,'lower presets respect aggregate budget');
let running=0,max=0;
const jobs=Array.from({length:4},()=>queueModelLoad(async()=>{max=Math.max(max,++running);await new Promise(r=>setTimeout(r,5));running--}));
await Promise.all(jobs);assert.equal(max,1,'only one model decode across scenes');
let calls=0,closed=0,active=0,maxDecode=0,current=true;
const textures=[];
const parser={loadImageSource:async()=>{calls++;maxDecode=Math.max(maxDecode,++active);await new Promise(r=>setTimeout(r,5));active--;const source={data:{width:4096,height:4096,close(){closed++}}};const t={source,get image(){return source.data},set image(i){source.data=i},clone(){return {...this,source}},dispose(){}};textures.push(t);return t}};
const release=budgetImageDecoding(parser,1024,()=>current);
const [a,b,c]=await Promise.all([parser.loadImageSource(0),parser.loadImageSource(1),parser.loadImageSource(0)]);
assert.equal(calls,2);assert.equal(maxDecode,1);assert.equal(closed,2);assert.equal(a.image.width,1024);assert.equal(c.source,a.source,'shared source must reference resized image');
current=false;await assert.rejects(parser.loadImageSource(2));assert.equal(calls,2,'cancelled scene must not decode another image');release();
let failure;
const broken={loadImageSource:async()=>{throw new Error('decoder failure')}};
budgetImageDecoding(broken,4096,()=>true,error=>{failure=error});
await assert.rejects(broken.loadImageSource(0));assert.equal(failure.message,'decoder failure','GLTF texture failures must not silently render an untextured success');
const compressed={image:{width:4096,height:4096},isCompressedTexture:true,dispose(){}};
const gpuParser={loadImageSource:async()=>compressed};budgetImageDecoding(gpuParser,4096,()=>true);
assert.equal((await gpuParser.loadImageSource(0)).image.width,4096,'compressed source must never go through canvas drawImage');
const unsupported={loadImageSource:async()=>compressed};budgetImageDecoding(unsupported,2048,()=>true);
await assert.rejects(unsupported.loadImageSource(0),/源贴图尺寸/,'oversized compressed texture must not reach GPU upload');
let geometry=0,material=0,texture=0,image=0;
const tex={isTexture:true,image:{close(){image++}},dispose(){texture++}};
disposeModel({traverse(fn){fn({geometry:{dispose(){geometry++}},material:{map:tex,normalMap:tex,dispose(){material++}}})}});
assert.deepEqual([geometry,material,texture,image],[1,1,1,1]);
const old=beginHeavyLoad('mp45'),newest=beginHeavyLoad('mp45');finishHeavyLoad(old);assert.equal(interruptedHeavyLoad('mp45'),true,'stale success cannot clear latest guard');
const done=beginHeavyLoad('mp45');finishHeavyLoad(done);assert.equal(interruptedHeavyLoad('mp45'),false);
beginHeavyLoad('mp45');assert.equal(interruptedHeavyLoad('other'),false);assert.equal(interruptedHeavyLoad('mp45'),true);
console.log('PASS serial model/image decoding, shared image release, cancellation, RAW dimensions, interrupted-load guard');
})().catch(e=>{console.error(e);process.exit(1)});
