const assert = require('node:assert/strict');
const fs = require('node:fs'), ts = require('typescript'), Module = require('node:module');
const m = new Module(__filename, module);
m._compile(ts.transpileModule(fs.readFileSync('components/showcase/modelMemory.ts','utf8'), { compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020} }).outputText,__filename);
const {requiresOriginalGpu,rememberWorkingQuality,recoveryQuality,textureLimit,queueModelLoad,budgetImageDecoding,disposeModel}=m.exports;
class Canvas {constructor(){this.width=1;this.height=1}getContext(){return {drawImage(){}}}}
global.HTMLCanvasElement=Canvas;global.document={createElement:()=>new Canvas()};
const entries=new Map();global.sessionStorage={getItem:k=>entries.get(k)??null,setItem:(k,v)=>entries.set(k,v),removeItem:k=>entries.delete(k)};
(async()=>{
for(const requested of [1024,2048,4096,16384]) assert.equal(textureLimit(requested,16384),requested,'selected quality must not be reduced by touch hardware');
assert.equal(textureLimit(16384,8192),8192,'only actual GPU capability caps the source size');
for(const file of ['mclaren_mp45__formula_1.glb','mclaren_mp45__formula_1-uastc.glb']) {
  for(const quality of [1024,2048,4096]) assert.equal(requiresOriginalGpu('/uploads/mclaren/models/'+file+'?v=1',quality,true),false);
  assert.equal(requiresOriginalGpu('/uploads/mclaren/models/'+file+'?v=1',16384,true),true);
  assert.equal(requiresOriginalGpu('/uploads/mclaren/models/'+file+'?v=1',16384,false),false);
}
for(const file of ['gulf_mclaren_f1_2022_car.glb','mclaren_mp46.glb','mcl35m.glb','uploaded-model.glb']) assert.equal(requiresOriginalGpu('/uploads/'+file,16384,true),false,'other cars retain original quality');
assert.equal(recoveryQuality('unknown','original'),null,'never invent a successful 1K fallback');
rememberWorkingQuality('mp45','balanced');rememberWorkingQuality('mp45','fine');rememberWorkingQuality('mp45','original');
assert.equal(recoveryQuality('mp45','original'),'fine');
assert.equal(recoveryQuality('mp45','fine'),'balanced','repeated failure must skip already failed qualities');
assert.equal(recoveryQuality('mp45','balanced'),null,'stop after verified candidates are exhausted');
assert.equal(recoveryQuality('other-car','original'),null,'successful qualities cannot leak between models');
rememberWorkingQuality('mp45','fine');assert.equal(recoveryQuality('mp45','original'),'fine','manual successful retry restores eligibility');
let running=0,max=0;
const jobs=Array.from({length:4},()=>queueModelLoad(async()=>{max=Math.max(max,++running);await new Promise(r=>setTimeout(r,5));running--}));
await Promise.all(jobs);assert.equal(max,1,'only one model decode across scenes');
await assert.rejects(queueModelLoad(() => new Promise(() => {}), 20), /高清模型解析超时/, 'stalled decoder must terminate the visible switch');
assert.equal(await queueModelLoad(async () => 'next-model'), 'next-model', 'a timed-out decoder must not block the next quality choice');
let calls=0,closed=0,active=0,maxDecode=0,current=true;
const textures=[];
const parser={loadImageSource:async()=>{calls++;maxDecode=Math.max(maxDecode,++active);await new Promise(r=>setTimeout(r,5));active--;const source={data:{width:4096,height:4096,close(){closed++}}};const t={source,get image(){return source.data},set image(i){source.data=i},clone(){return {...this,source}},dispose(){}};textures.push(t);return t}};
const release=budgetImageDecoding(parser,1024,()=>current);
const [a,b,c]=await Promise.all([parser.loadImageSource(0),parser.loadImageSource(1),parser.loadImageSource(0)]);
assert.equal(calls,2);assert.equal(maxDecode,1);assert.equal(closed,2);assert.equal(a.image.width,1024);assert.equal(c.source,a.source,'shared source must reference resized image');
current=false;await assert.rejects(parser.loadImageSource(2));assert.equal(calls,2,'cancelled scene must not decode another image');release();
let failure;
const broken={loadImageSource:async()=>{throw new Error('decoder failure')}};
budgetImageDecoding(broken,4096,()=>true,error=>{failure=error});
await assert.rejects(broken.loadImageSource(0));assert.equal(failure.message,'decoder failure','GLTF texture failures must not silently render an untextured success');
const compressed={image:{width:4096,height:4096},isCompressedTexture:true,dispose(){}};
const gpuParser={loadImageSource:async()=>compressed};budgetImageDecoding(gpuParser,4096,()=>true);
assert.equal((await gpuParser.loadImageSource(0)).image.width,4096,'compressed source must never go through canvas drawImage');
const unsupported={loadImageSource:async()=>compressed};budgetImageDecoding(unsupported,2048,()=>true);
await assert.rejects(unsupported.loadImageSource(0),/源贴图尺寸/,'oversized compressed texture must not reach GPU upload');
let geometry=0,material=0,texture=0,image=0;
const tex={isTexture:true,image:{close(){image++}},dispose(){texture++}};
disposeModel({traverse(fn){fn({geometry:{dispose(){geometry++}},material:{map:tex,normalMap:tex,dispose(){material++}}})}});
assert.deepEqual([geometry,material,texture,image],[1,1,1,1]);
console.log('PASS serial model/image decoding, shared image release, cancellation, all quality dimensions, MP4/5-only protection');
})().catch(e=>{console.error(e);process.exit(1)});
